@startuml
package "Architektura 3DSoftViz" {

[Manager] -left- [Model]
[Model] -left- [PostgreSQL]
[Manager] - [Importer]
[Manager] -down- [Data]
[Data] -left- [Layout]
[Data] - [Clustering]
[Data] -down- [Viewer]
[Viewer] -left- [Core]
[Layout] -down- [Core]
[Core] -down- [QOSG]
[QOSG] -up- [Viewer]
[Viewer] -down- [QOpenCV]
[QOSG] - [QOpenCV]
[QOpenCV] -down- [OpenCV]
[QOpenCV] -down- [Aruco]
[Viewer] - [LuaGraph]
[Viewer] - [Network]
[Math] -left- [Viewer]
[Kinect] -left- [Viewer]
[Viewer] - [Leap]
[Leap] -down- [QOSG]
[Kinect] -down- [QOSG]

[City] -left- [Viewer]
[City] -down- [QOSG]
[City] -up- [Data]

}
@enduml