@startuml

package Git {

package GitLib {
GitEvolutionGraph -down- GitUtils
GitEvolutionGraph *-down- GitVersion
GitVersion *-down- GitFile
GitFile -up- GitType
GitFile *-down- GitFileDiffBlock
GitFile -down- GitFileLoader
GitFile *-down- GitFunction
GitFunction *-- GitFunction
GitFunction -down- GitFunctionType
GitFileDiffBlock -down- GitFileLoader
GitFileDiffBlock *-down- GitFileDiffBlockLine
GitFileDiffBlockLine -down- GitFileLoader
GitFileDiffBlockLine -up- GitType
GitVersion -down- GitFileLoader
GitEvolutionGraph -down- GitEvolutionGraphManager
GitEvolutionGraph -down- GitMetaData
}

GitGraphUpdater -left- GitEvolutionGraph
GitGraphUpdater -left- GitType
GitGraphUpdater -left- GitFile
GitGraphUpdater - GitVersion
}

package Data {
Node - GitGraphUpdater
Edge - GitGraphUpdater
Graph - GitGraphUpdater
}

package Manager {
Manager - GitGraphUpdater
}

package Importer {
GraphOperations - GitGraphUpdater
}

@enduml
