// Module Graph.structure.layer3.Edge
// Autor: Aug_RealityKings

@startuml
object "edge:Data::Edge:osg::Switch" as obj1
object "srcNode:Data::Node" as obj2
object "dstNode:Data::Node" as obj3
object "camera:osg::Camera" as obj4
object "coordinates:osg::Vec3Array" as obj5
object "edgeTexCoords:osg::Vec2Array" as obj6
object "rotation:osg::Vec3Array" as obj7
object "center:osg::Vec3Array" as obj8
object "edgeColor:osg::Vec4" as obj9
object "label:osg::Geode" as obj10
object "label:osgText::FadeText" as obj11
object "quad:osg::Geode" as obj12
object "nodeQuad:osg::Geometry" as obj13
object "cylinder:osg::Geode" as obj14
object "nodeCylinder:osg::ShapeDrawable" as obj15
object "line:osg::Geode" as obj16
object "nodeLine:osg::Geometry" as obj17
object "curve:osg::Geode" as obj18
object "nodeCurve:osg::Geometry" as obj19

object "cylinder:osg::Cylinder" as obj20

obj1 o-- obj2
obj1 o-- obj3
obj1 o-- obj4
obj1 o-- obj5
obj1 o-- obj6
obj1 o-- obj7
obj1 o-- obj8
obj1 o-- obj9
obj1 o-- obj10
obj10 o-- obj11
obj1 o-- obj12
obj12 o-- obj13
obj1 o-- obj14
obj14 o-- obj15
obj1 o-- obj16
obj16 o-- obj17
obj1 o-- obj18
obj18 o-- obj19

obj15 o-- obj20


note top of obj10
V pripade moznosti: INDEX_LABEL
end note

note top of obj12
V pripade moznosti: INDEX_QUAD
end note

note top of obj14
V pripade moznosti: INDEX_CYLINDER
end note

note top of obj16
V pripade moznosti: INDEX_LINE
end note

note top of obj18
V pripade moznosti: INDEX_CURVE
end note
@enduml