// Module hand2
// Autor: Aug_RealityKings


@startuml
object "handNode:HandNode" as obj1
object "transform:MatrixTransform" as obj2
object "geode:osg::Geode" as obj3
object "shape:osg::ShapeDrawable" as obj4
object "sphere:osg::Sphere" as obj5


object "joint:HandNode" as obj6
obj6 : level = (-1,3)
obj6 : position = (0-5)

object "edge:DataEdge" as obj7
object "cylinder:Geode" as obj8
object "shape:osg::ShapeDrawable" as obj9
object "cylinder:osg::Cylinder" as obj10
object "transform:MatrixTransform" as obj11



obj1 o-- obj2
obj2 o-- obj3
obj3 o-- obj4
obj4 o-- obj5

obj7 <.. obj6
obj7 o-- obj11
obj11 o-- obj8
obj8 o-- obj9
obj9 o-- obj10


@enduml